apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: userservice  # Adjusted to match the correct label
  ports:
    - protocol: TCP
      port: 5117
      targetPort: 80
      name: http-port
    - protocol: TCP
      port: 7117
      targetPort: 443
      name: https-port
    - name: postgres-service-user 
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer



