apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: userservice  
  ports:
    - protocol: TCP
      port: 5118
      targetPort: 80
      name: http-port
    - protocol: TCP
      port: 7118
      targetPort: 443
      name: https-port
  type: ClusterIP



